<?php

// Single source of truth for the From/To dropdown lists used across the
// manual trip planner (step 1 and step 2 legs) and the traveler-facing
// Destinations browser, so both always show the exact same set of cities
// instead of drifting apart.
return [
    'local' => [
        ['name' => 'Manila',           'code' => 'MNL', 'country' => 'Philippines'],
        ['name' => 'Cebu City',        'code' => 'CEB', 'country' => 'Philippines'],
        ['name' => 'Davao City',       'code' => 'DVO', 'country' => 'Philippines'],
        ['name' => 'Boracay',          'code' => 'KLO', 'country' => 'Philippines'],
        ['name' => 'Puerto Princesa',  'code' => 'PPS', 'country' => 'Philippines'],
        ['name' => 'Tagbilaran',       'code' => 'TAG', 'country' => 'Philippines'],
        ['name' => 'Siargao',          'code' => 'IAO', 'country' => 'Philippines'],
        ['name' => 'Iloilo City',      'code' => 'ILO', 'country' => 'Philippines'],
        ['name' => 'Bacolod',          'code' => 'BCD', 'country' => 'Philippines'],
        ['name' => 'Zamboanga',        'code' => 'ZAM', 'country' => 'Philippines'],
        ['name' => 'Cagayan de Oro',   'code' => 'CGY', 'country' => 'Philippines'],
        ['name' => 'General Santos',   'code' => 'GES', 'country' => 'Philippines'],
        ['name' => 'Tacloban',         'code' => 'TAC', 'country' => 'Philippines'],
        ['name' => 'Dumaguete',        'code' => 'DGT', 'country' => 'Philippines'],
        ['name' => 'El Nido',          'code' => 'ENI', 'country' => 'Philippines'],
        ['name' => 'Coron',            'code' => 'USU', 'country' => 'Philippines'],
        ['name' => 'Baguio',           'code' => 'BAG', 'country' => 'Philippines'],
        ['name' => 'Tagaytay',         'code' => 'MNL', 'country' => 'Philippines'],
        ['name' => 'Vigan',            'code' => 'VIG', 'country' => 'Philippines'],
        ['name' => 'Batanes',          'code' => 'BSO', 'country' => 'Philippines'],
        ['name' => 'Camiguin',         'code' => 'CGM', 'country' => 'Philippines'],
        ['name' => 'Siquijor',         'code' => 'DGT', 'country' => 'Philippines'],
        ['name' => 'Surigao',          'code' => 'SUG', 'country' => 'Philippines'],
        ['name' => 'Laoag',            'code' => 'LAO', 'country' => 'Philippines'],
        ['name' => 'Legazpi',          'code' => 'LGP', 'country' => 'Philippines'],
    ],
    'intl' => [
        ['name' => 'Singapore',            'code' => 'SIN', 'country' => 'Singapore'],
        ['name' => 'Bangkok',              'code' => 'BKK', 'country' => 'Thailand'],
        ['name' => 'Bali',                 'code' => 'DPS', 'country' => 'Indonesia'],
        ['name' => 'Tokyo',                'code' => 'NRT', 'country' => 'Japan'],
        ['name' => 'Seoul',                'code' => 'ICN', 'country' => 'South Korea'],
        ['name' => 'Kuala Lumpur',         'code' => 'KUL', 'country' => 'Malaysia'],
        ['name' => 'Hong Kong',            'code' => 'HKG', 'country' => 'Hong Kong'],
        ['name' => 'Dubai',                'code' => 'DXB', 'country' => 'United Arab Emirates'],
        ['name' => 'London',               'code' => 'LHR', 'country' => 'United Kingdom'],
        ['name' => 'Paris',                'code' => 'CDG', 'country' => 'France'],
        ['name' => 'New York',             'code' => 'JFK', 'country' => 'United States'],
        ['name' => 'Sydney',               'code' => 'SYD', 'country' => 'Australia'],
        ['name' => 'Osaka',                'code' => 'KIX', 'country' => 'Japan'],
        ['name' => 'Taipei',               'code' => 'TPE', 'country' => 'Taiwan'],
        ['name' => 'Rome',                 'code' => 'FCO', 'country' => 'Italy'],
        ['name' => 'Barcelona',            'code' => 'BCN', 'country' => 'Spain'],
        ['name' => 'Amsterdam',            'code' => 'AMS', 'country' => 'Netherlands'],
        ['name' => 'Maldives',             'code' => 'MLE', 'country' => 'Maldives'],
        ['name' => 'Phuket',               'code' => 'HKT', 'country' => 'Thailand'],
        ['name' => 'Ho Chi Minh City',     'code' => 'SGN', 'country' => 'Vietnam'],
        ['name' => 'Hanoi',                'code' => 'HAN', 'country' => 'Vietnam'],
        ['name' => 'Doha',                 'code' => 'DOH', 'country' => 'Qatar'],
        ['name' => 'Istanbul',             'code' => 'IST', 'country' => 'Turkey'],
        ['name' => 'Toronto',              'code' => 'YYZ', 'country' => 'Canada'],
        ['name' => 'Los Angeles',          'code' => 'LAX', 'country' => 'United States'],
    ],
];
